### ISSUE TITLE
Return code 11 and HTTP code 500 returned when sending a setDoorState() request

### ISSUE THREAD

**Issue by idanielgarcia13** [thomasmunduchira/myq-api#12]
Hi Thomas!

This is my first time working on a node.js project on my own so I apologize if I'm doing something incorrectly or if my code style is a bit odd.

I am able to use the 'myq-api' just fine and can login() & getdevices() just fine but when I go to set the door state, I get a 500 internal server error. In your repo, it says to create a github issue if you see this. I included the output below.

`{ returnCode: 0, token: 'removing-this-for-security-reasons' }
{ returnCode: 0,
  devices:
   [ { id: removing-this-for-security-reasons,
       typeId: 7,
       typeName: 'VGDO',
       serialNumber: 'removing-this-for-security-reasons',
       online: true,
       doorState: 2,
       doorStateDescription: 'closed',
       doorStateUpdated: 1597624376755,
       name: 'Garage Door' } ] }
{ returnCode: 11,
  message:
   'Something unexpected happened. Please wait a bit and try again.',
  unhandledError:
   { Error: Request failed with status code 500
       at createError (/Users/danielgarcia/Documents/garage-door-controller/node_modules/axios/lib/core/createError.js:16:15)
       at settle (/Users/danielgarcia/Documents/garage-door-controller/node_modules/axios/lib/core/settle.js:18:12)
       at IncomingMessage.handleStreamEnd (/Users/danielgarcia/Documents/garage-door-controller/node_modules/axios/lib/adapters/http.js:201:11)
       at IncomingMessage.emit (events.js:203:15)
       at endReadableNT (_stream_readable.js:1145:12)
       at process._tickCallback (internal/process/next_tick.js:63:19)
     config:
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        method: 'put',
        url:
         'https://myqexternal.myqdevice.com/api/v4/deviceattribute/putdeviceattribute',
        data:
         '{"MyQDeviceId":"removing-this-for-security-reasons","AttributeName":"desireddoorstate","AttributeValue":1}' },
     request:
      ClientRequest {
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header:
         'PUT /api/v4/deviceattribute/putdeviceattribute HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/json;charset=utf-8\r\nMyQApplicationId: NWknvuBd7LoFHfXmKNMBcgajXtZEgKUh4V7WNzMidrpUUluDpVYVZx+xT4PCM5Kx\r\nSecurityToken: 871ca9f0-ed35-4c87-9ba1-5f0637753388\r\nUser-Agent: axios/0.18.0\r\nContent-Length: 84\r\nHost: myqexternal.myqdevice.com\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'PUT',
        insecureHTTPParser: undefined,
        path: '/api/v4/deviceattribute/putdeviceattribute',
        _ended: true,
        res: [IncomingMessage],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Writable],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     response:
      { status: 500,
        statusText: 'Internal Server Error',
        headers: [Object],
        config: [Object],
        request: [ClientRequest],
        data: [Object] } } }
`

**Comment by thomasmunduchira** [comment]
Hi there @idanielgarcia13 - welcome to the community!

Thanks for reporting this 500 error. I was able to replicate this by passing in an invalid/nonexistent `id` to `setDoorState`. Would you be able to share the relevant code that uses `myq-api`? I suspect you’re not passing in a valid device ID to `setDoorState`.

I’m also very surprised that the current npm package is working now since the v4 endpoint that this module was built on stopped working a month ago: https://github.com/thomasmunduchira/myq-api/pull/3#pullrequestreview-444441644.  Guess it is back up now, but support for the v5 endpoint will still be rolled out imminently via an update to the npm package.

**Comment by thomasmunduchira** [comment]
@idanielgarcia13, I have cut a new release that should report this error more gracefully: [myq-api](https://www.npmjs.com/package/myq-api). I will close this for now, but please reopen if this issue persists.
