### ISSUE TITLE
How short-lived is short-lived security token?

### ISSUE THREAD

**Issue by techied** [thomasmunduchira/myq-api#25]
I'm developing [myq-api-relay](https://github.com/techied/myq-api-relay) with this module.

Would it be okay to log in once, and then over the course of many hours or days, call other functions without logging in, or does the security token only last a matter of minutes?

Thanks

**Comment by SYNTAG** [comment]
I was wondering this too. I couldn't find any information on the timeframe. But I do know that it's at least it's not longer than 2 hours.

**Comment by brbeaird** [comment]
For what it's worth - last I messed with this on my own integration, I think I found it sometimes living as short as 15 minutes. It seemed like they really shortened it with the move to V5.

**Comment by SYNTAG** [comment]
@brbeaird Interesting... for me in my tests I found it lived longer than that. I'll try to confirm today and report back here with the results.

**Comment by thomasmunduchira** [comment]
Great question @techied! I ran a quick test since I didn't know myself. Looks like @brbeaird is on the money - the security token expired after 15 minutes for me.

Marking this closed since the question is answered, but happy to have a discussion around the consequences of this.

**Comment by techied** [comment]
Thanks for the research @thomasmunduchira !
