### ISSUE TITLE
TS Support?

### ISSUE THREAD

**Issue by JLuboff** [thomasmunduchira/myq-api#26]
Just curious if Typescript support (typings) will be added at any point or if I should consider creating them to and pushing to DefinitelyTyped?

**Comment by thomasmunduchira** [comment]
Thanks for bringing this up, @JLuboff. I fielded a similar question in #3: [comment](https://github.com/thomasmunduchira/myq-api/pull/3#issuecomment-657122508). Looping in @kn0ll who also graciously offered to add TypeScript support to this module.

I am pretty new to the TypeScript world so it would be great if one or both of you could make the initial contributions here. I would be more than happy to build on top of/maintain it for future versions.

I haven't heard of DefinitelyTyped before this, but based on https://stackoverflow.com/questions/56834190, I think adding the types to the module itself would provide a better experience. Happy to hear thoughts on this, however.

**Comment by kn0ll** [comment]
@thomasmunduchira 

if your open to using TypeScript as your primary host language for this repository (whose main side effect will be a compilation step), that is definitely the right option to go.

the only reason to use DefinitelyTyped is if you can't get a project maintainer to support it natively. it sounds like you are on board though!

now that the dust has settled on the rewrite, i am happy to give it a shot. i can have some demonstrable results we can start discussing by the end of next week if you are interested. cheers!

**Comment by kn0ll** [comment]
started work [here](https://github.com/kn0ll/myq-api/tree/typescript
). while all the code has actually been converted already, the devil is in the details. necessary remaining items from my POV is:

- more type improvements, specifically around things that get returned through the public API:
  - the new `Device` type (name pending)
  - MyQ api responses
- adding typescript to eslint configuration
- making sure it builds and ships the correct files & manifests to NPM is the tricky part i will work on in the coming days

my priority was to change as little code as possible. i think it would be smart to intend to release that way. but in future builds, we could take advantage of some typescript features like [optional chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html), [Enum](https://www.typescriptlang.org/docs/handbook/enums.html) and more to modernize some of the code.

**Comment by JLuboff** [comment]
Thank you to both. @kn0ll if I find some time, I'd like to contribute as well. If I do, would you want me to PR against your repo?

**Comment by kn0ll** [comment]
that would be awesome. let me know here what you plan to tackle so we don't overlap. but yeah, would love a hand, a PR on my fork (branch: `typescript`) sounds great. ✋
