### ISSUE TITLE
myq-api returning ERR_MYQ_SERVICE_UNREACHABLE

### ISSUE THREAD

**Issue by thomasmunduchira** [thomasmunduchira/myq-api#28]
This module is now returning ERR_MYQ_SERVICE_UNREACHABLE per the last two days of E2E cron tests. See the [latest run](https://github.com/thomasmunduchira/myq-api/actions/runs/430782970) as an example.

Based on related repos, there appears to be upstream API changes. Assuming there is an agreed upon fix that is relatively trivial, I should be able to land and deploy a new version by end of day.

**Comment by nsnyder** [comment]
Thanks! I had noticed this yesterday and came by to open a ticket. Let me know if you need a hand!

**Comment by JamsheedMistri** [comment]
Also receiving this error

**Comment by thomasmunduchira** [comment]
Looks like the [okhttp/3.10.0 user agent](https://github.com/thomasmunduchira/myq-api/blob/642e44f5e8926898228dc38019c230c8bdf90bf5/src/constants.js#L45) is being blocklisted now: [pymyq pull #54](https://github.com/arraylabs/pymyq/pull/54#issue-541513207). The official Android client is now using `okhttp/3.12.1` as the user agent: [pymyq pull #54](https://github.com/arraylabs/pymyq/pull/54#issuecomment-748279366). It appears as if the old user agent is being blocklisted to force users to update.

The new user agent will work until they invariably blocklist the new user agent a few months down the line. We can instead generate random user agents as the following projects have opted to do in order to mitigate:
* [pymyq](https://github.com/arraylabs/pymyq/commit/a0197aea3deaa3d993095620edc4660d329bff1f)
* [homebridge-myq](https://github.com/hjdhjd/homebridge-myq/commit/05970278f719e2d6335af129f852e187140c1f55)

This _could_ backfire if myQ switches from a blocklist to an allowlist, but only time will tell. I will proceed with this approach for now.

**Comment by thomasmunduchira** [comment]
I cut release 2.0.3 and verified it to be working.

**Comment by nsnyder** [comment]
Thanks, @thomasmunduchira! Working beautifully!

**Comment by sergeichestakov** [comment]
Sweet! Thanks @thomasmunduchira
